// Generated by scripts/generate-contracts.py; do not edit by hand.

export const LABEL_DICTIONARY_VERSION = "chexpert-14-v1" as const;

export const LABEL_DEFINITIONS = [
  {
    "key": "Atelectasis",
    "zh": "肺不张",
    "en": "Atelectasis",
    "kind": "abnormality",
    "primary": true
  },
  {
    "key": "Cardiomegaly",
    "zh": "心脏增大",
    "en": "Cardiomegaly",
    "kind": "abnormality",
    "primary": true
  },
  {
    "key": "Consolidation",
    "zh": "实变",
    "en": "Consolidation",
    "kind": "abnormality",
    "primary": true
  },
  {
    "key": "Edema",
    "zh": "水肿",
    "en": "Edema",
    "kind": "abnormality",
    "primary": true
  },
  {
    "key": "Enlarged Cardiomediastinum",
    "zh": "纵隔增宽",
    "en": "Enlarged Cardiomediastinum",
    "kind": "abnormality",
    "primary": false
  },
  {
    "key": "Fracture",
    "zh": "骨折",
    "en": "Fracture",
    "kind": "abnormality",
    "primary": false
  },
  {
    "key": "Lung Lesion",
    "zh": "肺部病灶",
    "en": "Lung Lesion",
    "kind": "abnormality",
    "primary": false
  },
  {
    "key": "Lung Opacity",
    "zh": "肺部阴影",
    "en": "Lung Opacity",
    "kind": "abnormality",
    "primary": false
  },
  {
    "key": "No Finding",
    "zh": "未见异常",
    "en": "No Finding",
    "kind": "status",
    "primary": false
  },
  {
    "key": "Pleural Effusion",
    "zh": "胸腔积液",
    "en": "Pleural Effusion",
    "kind": "abnormality",
    "primary": true
  },
  {
    "key": "Pleural Other",
    "zh": "其他胸膜病变",
    "en": "Pleural Other",
    "kind": "abnormality",
    "primary": false
  },
  {
    "key": "Pneumonia",
    "zh": "肺炎",
    "en": "Pneumonia",
    "kind": "abnormality",
    "primary": false
  },
  {
    "key": "Pneumothorax",
    "zh": "气胸",
    "en": "Pneumothorax",
    "kind": "abnormality",
    "primary": false
  },
  {
    "key": "Support Devices",
    "zh": "支持性器械",
    "en": "Support Devices",
    "kind": "status",
    "primary": false
  }
] as const;

export const CHEXPERT_LABELS = LABEL_DEFINITIONS.map(({ key }) => key);

export type CheXpertLabel = (typeof LABEL_DEFINITIONS)[number]["key"];

export type ReviewDecision = "confirmed" | "denied" | "uncertain";

export type ConfigValue = string | number | boolean | null | Array<string | number | boolean | null>;

export interface MetricInterval { estimate: number | null; lower: number | null; upper: number | null; n: number; }

export type MetricValue = number | null | MetricInterval;

export interface CurvePoint { x: number; y: number; threshold?: number | null; }

export interface CurveSeries { label: "Atelectasis" | "Cardiomegaly" | "Consolidation" | "Edema" | "Enlarged Cardiomediastinum" | "Fracture" | "Lung Lesion" | "Lung Opacity" | "No Finding" | "Pleural Effusion" | "Pleural Other" | "Pneumonia" | "Pneumothorax" | "Support Devices"; method: "baseline" | "mixstyle"; seed: number; roc: Array<CurvePoint>; pr: Array<CurvePoint>; }

export type ModelCardValue = string | Array<string>;

export interface ExperimentBundle { schemaVersion: "medexperiment-1"; experimentId: string; config: Record<string, ConfigValue>; seeds: Array<number>; datasetManifestSha256: string; aggregateMetrics: Record<string, number | null>; perClassMetrics: Partial<Record<CheXpertLabel, Record<string, MetricValue>>>; curves: Record<string, CurveSeries>; modelCard: { intendedUse?: string; limitations?: Array<string>; [key: string]: ModelCardValue | undefined; }; }

export interface ModelManifest { schemaVersion: "medmodel-1"; modelId: string; version: string; architecture: "densenet121"; labels: readonly ["Atelectasis", "Cardiomegaly", "Consolidation", "Edema", "Enlarged Cardiomediastinum", "Fracture", "Lung Lesion", "Lung Opacity", "No Finding", "Pleural Effusion", "Pleural Other", "Pneumonia", "Pneumothorax", "Support Devices"]; input: { width: 320; height: 320; channels: 1; normalization: "imagenet-gray"; }; thresholds: Record<CheXpertLabel, number>; preprocessing: { viewPositions: readonly ["AP", "PA"]; adultOnly: true; }; training: { commit: string; seeds: Array<number>; method: "baseline" | "mixstyle"; }; dataSources: Array<string>; license: string; files: { "model.onnx": string; "labels.json": string; [key: string]: string; }; modelSha256: string; manifestSha256: string; }

export interface PredictionCam { label: "Atelectasis" | "Cardiomegaly" | "Consolidation" | "Edema" | "Enlarged Cardiomediastinum" | "Fracture" | "Lung Lesion" | "Lung Opacity" | "No Finding" | "Pleural Effusion" | "Pleural Other" | "Pneumonia" | "Pneumothorax" | "Support Devices"; width: number; height: number; pixelsBase64: string; sha256: string; }

export interface Prediction { predictionId: string; studyId: string; modelId: string; modelVersion: string; modelSha256: string; manifestSha256: string; createdAt: string; probabilities: Record<CheXpertLabel, number | null>; logits: Record<CheXpertLabel, number | null>; thresholds: Record<CheXpertLabel, number>; camAvailable: boolean; source: "onnx"; }

export interface ReportRevision { reportId: string; studyId: string; revision: number; authorId: string; createdAt: string; body: string; status: "draft" | "confirmed"; confirmedAt?: string | null; reviewId?: string | null; }

export interface Review { reviewId: string; studyId: string; predictionId: string; doctorId: string; createdAt: string; decisions: Partial<Record<CheXpertLabel, "confirmed" | "denied" | "uncertain">>; notes: string; }

export interface Study { studyId: string; createdAt: string; modality: "DX" | "CR" | "CT" | "UNKNOWN"; bodyPart: "CHEST" | "UNKNOWN"; viewPosition: "AP" | "PA" | "UNKNOWN"; adultConfirmed: boolean; status: "staged" | "ready" | "rejected" | "reviewed"; }
