from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Mapping

ROOT = Path(__file__).resolve().parents[1]
LABELS_PATH = ROOT / "contracts" / "labels.json"
SCHEMA_DIRECTORY = ROOT / "contracts" / "schemas"
PYTHON_OUTPUT = ROOT / "ml" / "cxr_research" / "labels.py"
SHARED_TYPES_OUTPUT = ROOT / "contracts" / "types.ts"
DESKTOP_OUTPUT = ROOT / "apps" / "desktop" / "src" / "generated" / "contracts.ts"
GENERATED_NOTICE = "Generated by scripts/generate-contracts.py; do not edit by hand."


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _schema_name(path: Path) -> str:
    suffix = ".schema.json"
    if not path.name.endswith(suffix):
        raise ValueError(f"unexpected schema file name: {path.name}")
    return path.name[: -len(suffix)]


def _pascal_case(value: str) -> str:
    pieces = re.split(r"[^A-Za-z0-9]+", value)
    return "".join(piece[:1].upper() + piece[1:] for piece in pieces if piece)


def _property_name(value: str) -> str:
    return value if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", value) else json.dumps(value)


def _typescript_literal(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "readonly [" + ", ".join(_typescript_literal(item) for item in value) + "]"
    raise ValueError(f"unsupported JSON Schema const value: {value!r}")


def _definition_name(reference: str) -> str:
    prefix = "#/$defs/"
    if not reference.startswith(prefix):
        raise ValueError(f"only local $defs references are supported: {reference}")
    return _pascal_case(reference[len(prefix) :])


def _typescript_type(schema: Mapping[str, Any]) -> str:
    if "$ref" in schema:
        return _definition_name(str(schema["$ref"]))
    if "const" in schema:
        return _typescript_literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_typescript_literal(value) for value in schema["enum"])
    variants = schema.get("oneOf") or schema.get("anyOf")
    if variants:
        rendered: list[str] = []
        for variant in variants:
            candidate = _typescript_type(variant)
            if candidate not in rendered:
                rendered.append(candidate)
        return " | ".join(rendered)
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(
            _typescript_type({**schema, "type": candidate}) for candidate in schema_type
        )
    if schema_type == "string":
        return "string"
    if schema_type in {"number", "integer"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"Array<{_typescript_type(schema.get('items', {}))}>"
    if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
        return _typescript_object(schema)
    return "unknown"


def _typescript_object(schema: Mapping[str, Any]) -> str:
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    additional = schema.get("additionalProperties", True)
    property_names = schema.get("propertyNames", {})
    if not properties:
        if additional is False:
            return "Record<string, never>"
        value_type = "unknown" if additional is True else _typescript_type(additional)
        enum_names = property_names.get("enum")
        if enum_names == _canonical_label_keys:
            wrapper = "Record" if schema.get("minProperties") == len(_canonical_label_keys) else "Partial<Record"
            if wrapper == "Record":
                return f"Record<CheXpertLabel, {value_type}>"
            return f"Partial<Record<CheXpertLabel, {value_type}>>"
        return f"Record<string, {value_type}>"

    members: list[str] = []
    for name, property_schema in properties.items():
        optional = "" if name in required else "?"
        members.append(
            f"{_property_name(str(name))}{optional}: {_typescript_type(property_schema)};"
        )
    if additional is not False:
        value_type = "unknown" if additional is True else _typescript_type(additional)
        if any(name not in required for name in properties):
            value_type += " | undefined"
        members.append(f"[key: string]: {value_type};")
    return "{ " + " ".join(members) + " }"


def _render_interface(name: str, schema: Mapping[str, Any]) -> str:
    rendered = _typescript_type(schema)
    if rendered.startswith("{ ") and rendered.endswith(" }"):
        return f"export interface {name} {rendered}"
    return f"export type {name} = {rendered};"


def _schema_at(schema: Mapping[str, Any], *path: str) -> Any:
    current: Any = schema
    for item in path:
        current = current[item]
    return current


def _assert_label_consistency(
    labels: list[Mapping[str, Any]], schemas: Mapping[str, Mapping[str, Any]]
) -> None:
    expected = [str(item["key"]) for item in labels]
    if len(expected) != 14 or len(set(expected)) != len(expected):
        raise ValueError("contracts/labels.json must define exactly 14 unique labels")
    checks = {
        "model-manifest.labels": _schema_at(
            schemas["model-manifest"], "properties", "labels", "const"
        ),
        "model-manifest.thresholds": _schema_at(
            schemas["model-manifest"], "properties", "thresholds", "propertyNames", "enum"
        ),
        "prediction.probabilities": _schema_at(
            schemas["prediction"], "properties", "probabilities", "propertyNames", "enum"
        ),
        "prediction.logits": _schema_at(
            schemas["prediction"], "properties", "logits", "propertyNames", "enum"
        ),
        "prediction.thresholds": _schema_at(
            schemas["prediction"], "properties", "thresholds", "propertyNames", "enum"
        ),
        "prediction-cam.label": _schema_at(
            schemas["prediction-cam"], "properties", "label", "enum"
        ),
        "review.decisions": _schema_at(
            schemas["review"], "properties", "decisions", "propertyNames", "enum"
        ),
        "experiment.perClassMetrics": _schema_at(
            schemas["experiment-bundle"],
            "properties",
            "perClassMetrics",
            "propertyNames",
            "enum",
        ),
        "experiment.curveSeries.label": _schema_at(
            schemas["experiment-bundle"], "$defs", "curveSeries", "properties", "label", "enum"
        ),
    }
    mismatches = [name for name, actual in checks.items() if actual != expected]
    if mismatches:
        raise ValueError(
            "schema label order differs from contracts/labels.json: " + ", ".join(mismatches)
        )


def _render_python(
    label_document: Mapping[str, Any], schemas: Mapping[str, Mapping[str, Any]]
) -> str:
    definitions = []
    for item in label_document["labels"]:
        definitions.append(
            "    LabelDefinition("
            + ", ".join(
                repr(item[key]) for key in ("key", "zh", "en", "kind", "primary")
            )
            + "),"
        )
    schema_json = json.dumps(schemas, ensure_ascii=True, sort_keys=True, separators=(",", ":"))
    return f'''# {GENERATED_NOTICE}
from __future__ import annotations

import json
from dataclasses import dataclass
from math import isnan
from typing import Any, Final, Mapping

LABEL_DICTIONARY_VERSION: Final = {label_document["version"]!r}
CONTRACT_SCHEMAS: Final[dict[str, dict[str, Any]]] = json.loads(r\'''{schema_json}\''')


@dataclass(frozen=True)
class LabelDefinition:
    key: str
    zh: str
    en: str
    kind: str
    primary: bool


LABEL_DEFINITIONS: tuple[LabelDefinition, ...] = (
{chr(10).join(definitions)}
)

CHEXPERT_LABELS: tuple[str, ...] = tuple(item.key for item in LABEL_DEFINITIONS)
PRIMARY_LABELS: tuple[str, ...] = tuple(item.key for item in LABEL_DEFINITIONS if item.primary)
LABEL_INDEX = {{name: index for index, name in enumerate(CHEXPERT_LABELS)}}


def validate_label_order(labels: list[str] | tuple[str, ...]) -> None:
    """Reject partial, reordered, or foreign label dictionaries."""

    if tuple(labels) != CHEXPERT_LABELS:
        raise ValueError(
            "\u6a21\u578b\u5fc5\u987b\u4e25\u683c\u4f7f\u7528 CheXpert 14 \u9879\u6807\u7b7e\uff0c\u4e0d\u80fd\u91cd\u547d\u540d\u6216\u8865\u9f50\u5176\u4ed6\u6a21\u578b\u7684\u8f93\u51fa"
        )


def label_metadata(label: str) -> LabelDefinition:
    try:
        return LABEL_DEFINITIONS[LABEL_INDEX[label]]
    except KeyError as exc:
        raise KeyError(f"unknown CheXpert label: {{label}}") from exc


def parse_chexpert_value(value: Any) -> tuple[float, float]:
    """Return (target, mask) without converting uncertain labels to negatives."""

    if value is None:
        return 0.0, 0.0
    if isinstance(value, str):
        text = value.strip()
        if not text or text.lower() in {{"nan", "none", "null"}}:
            return 0.0, 0.0
        try:
            value = float(text)
        except ValueError as exc:
            raise ValueError(f"invalid CheXpert label value: {{value!r}}") from exc
    try:
        number = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"invalid CheXpert label value: {{value!r}}") from exc
    if isnan(number):
        return 0.0, 0.0
    if number == 1.0:
        return 1.0, 1.0
    if number == 0.0:
        return 0.0, 1.0
    if number == -1.0:
        return 0.0, 0.0
    raise ValueError(f"CheXpert labels must be -1, 0, 1, or blank; got {{value!r}}")


def encode_row(row: Mapping[str, Any]) -> tuple[list[float], list[float]]:
    targets: list[float] = []
    mask: list[float] = []
    for label in CHEXPERT_LABELS:
        target, valid = parse_chexpert_value(row.get(label))
        targets.append(target)
        mask.append(valid)
    return targets, mask
'''


def _review_decision_type(schemas: Mapping[str, Mapping[str, Any]]) -> str:
    values = _schema_at(
        schemas["review"], "properties", "decisions", "additionalProperties", "enum"
    )
    return " | ".join(_typescript_literal(value) for value in values)


def _render_typescript(
    label_document: Mapping[str, Any],
    schemas: Mapping[str, Mapping[str, Any]],
    *,
    include_schemas: bool,
) -> str:
    label_json = json.dumps(label_document["labels"], ensure_ascii=False, indent=2)
    sections = [
        f"// {GENERATED_NOTICE}",
        f"export const LABEL_DICTIONARY_VERSION = {json.dumps(label_document['version'])} as const;",
        f"export const LABEL_DEFINITIONS = {label_json} as const;",
        "export const CHEXPERT_LABELS = LABEL_DEFINITIONS.map(({ key }) => key);",
        'export type CheXpertLabel = (typeof LABEL_DEFINITIONS)[number]["key"];',
        f"export type ReviewDecision = {_review_decision_type(schemas)};",
    ]

    seen_definitions: dict[str, Mapping[str, Any]] = {}
    for schema in schemas.values():
        for definition_key, definition in schema.get("$defs", {}).items():
            name = _pascal_case(definition_key)
            previous = seen_definitions.get(name)
            if previous is not None and previous != definition:
                raise ValueError(f"conflicting JSON Schema definition name: {name}")
            seen_definitions[name] = definition
    for name, definition in seen_definitions.items():
        sections.append(_render_interface(name, definition))

    for schema_name, schema in schemas.items():
        sections.append(_render_interface(_pascal_case(schema_name), schema))

    if include_schemas:
        rendered_schemas = json.dumps(schemas, ensure_ascii=False, indent=2, sort_keys=True)
        sections.extend(
            [
                f"export const CONTRACT_SCHEMAS = {rendered_schemas} as const;",
                "export type ContractSchemaName = keyof typeof CONTRACT_SCHEMAS;",
            ]
        )
        for schema_name in schemas:
            constant = re.sub(r"[^A-Za-z0-9]+", "_", schema_name).upper() + "_SCHEMA"
            sections.append(
                f"export const {constant} = CONTRACT_SCHEMAS[{json.dumps(schema_name)}];"
            )
    return "\n\n".join(sections) + "\n"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Python and TypeScript contracts")
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when generated files are missing or stale without writing them",
    )
    args = parser.parse_args()

    label_document = _load_json(LABELS_PATH)
    schema_paths = sorted(SCHEMA_DIRECTORY.glob("*.schema.json"))
    schemas = {_schema_name(path): _load_json(path) for path in schema_paths}
    labels = label_document.get("labels")
    if not isinstance(labels, list):
        raise ValueError("contracts/labels.json must contain a labels array")
    global _canonical_label_keys
    _canonical_label_keys = [str(item["key"]) for item in labels]
    _assert_label_consistency(labels, schemas)

    outputs = {
        PYTHON_OUTPUT: _render_python(label_document, schemas),
        SHARED_TYPES_OUTPUT: _render_typescript(
            label_document, schemas, include_schemas=False
        ),
        DESKTOP_OUTPUT: _render_typescript(label_document, schemas, include_schemas=True),
    }
    if args.check:
        stale = [
            path
            for path, expected in outputs.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != expected
        ]
        if stale:
            for path in stale:
                print(f"stale generated contract: {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("generated contracts are current")
        return 0

    for path, content in outputs.items():
        _write(path, content)
        print(f"generated {path.relative_to(ROOT)}")
    return 0


_canonical_label_keys: list[str] = []


if __name__ == "__main__":
    raise SystemExit(main())
